version: "3.8"

services:
  postgres:
    image: postgres:14.5-alpine
    container_name: ecommerce-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Senha123
      - POSTGRES_DB=ecommerce
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
